version: "3.9"
services:
  api:
    build: .
    ports: 
      - 4000:4000

    environment:
      PORT: 4000
      MONGO_PASS: "Mongodb144"

    depends_on:
      - mongo_db

  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    # volumes: 
    #   - mongo_db:/data/db
      